module.exports = {
	"scenarios": [
		  {
			"label": "Configurator step summary",
			"cookiePath": "",
			"url": "http://hyundai/configurator/car/23/summary",
			"referenceUrl": "",
			"readyEvent": "",
			"readySelector": ".spritespin-canvas",
			"delay": 3500,
			"hideSelectors": [],
			"removeSelectors": [],
			"hoverSelector": "",
			"clickSelector": [],
			"postInteractionWait": 100,
			"selectors": [],
			"selectorExpansion": true,
			"expect": 0,
			"misMatchThreshold" : 0.1,
			"requireSameDimensions": true
		  },
		  {
			"label": "Configurator step test-drive popup",
			"cookiePath": "",
			"url": "http://hyundai/configurator/car/23/summary",
			"referenceUrl": "",
			"readyEvent": "",
			"readySelector": "",
			"delay": 5500,
			"onReadyScript": "puppet/onReady.js",
			"hideSelectors": [],
			"removeSelectors": [],
			"hoverSelector": "",
			"clickSelector": [".test-td-button"],
			"postInteractionWait": 5000,
			"selectors": [],
			"selectorExpansion": true,
			"expect": 0,
			"misMatchThreshold" : 0.1,
			"requireSameDimensions": true,
			"viewports": [{
				"label": "desctop",
				"width": 1920,
				"height": 1080
			}]
		  },
		  {
			"label": "Configurator step send popup",
			"cookiePath": "",
			"url": "http://hyundai/configurator/car/23/summary",
			"referenceUrl": "",
			"readyEvent": "",
			"readySelector": "",
			"delay": 5500,
			"onReadyScript": "puppet/onReady.js",
			"hideSelectors": [],
			"removeSelectors": [],
			"hoverSelector": "",
			"clickSelector": [".test-send-button"],
			"postInteractionWait": 5000,
			"selectors": [],
			"selectorExpansion": true,
			"expect": 0,
			"misMatchThreshold" : 0.1,
			"requireSameDimensions": true,
			"viewports": [{
				"label": "desctop",
				"width": 1920,
				"height": 1080
			}]
		  },
		  {
			"label": "Configurator step calculator test-drive popup",
			"cookiePath": "",
			"url": "http://hyundai/configurator/car/23/summary",
			"referenceUrl": "",
			"readyEvent": "",
			"readySelector": "",
			"delay": 5500,
			"onReadyScript": "puppet/onReady.js",
			"hideSelectors": [],
			"removeSelectors": [],
			"hoverSelector": "",
			"clickSelector": [".test-calc-button"],
			"postInteractionWait": 5000,
			"selectors": [],
			"selectorExpansion": true,
			"expect": 0,
			"misMatchThreshold" : 0.1,
			"requireSameDimensions": true,
			"viewports": [{
				"label": "desctop",
				"width": 1920,
				"height": 1080
			}]
		  },
		  {
			"label": "Configurator step calculator credit approval popup",
			"cookiePath": "",
			"url": "http://hyundai/configurator/car/23/summary",
			"referenceUrl": "",
			"readyEvent": "",
			"readySelector": "",
			"delay": 5500,
			"onReadyScript": "puppet/onReady.js",
			"hideSelectors": [],
			"removeSelectors": [],
			"hoverSelector": "",
			"clickSelector": [".test-calc-button", ".offer__button"],
			"postInteractionWait": 5000,
			"selectors": [],
			"selectorExpansion": true,
			"expect": 0,
			"misMatchThreshold" : 0.1,
			"requireSameDimensions": true,
			"viewports": [{
				"label": "desctop",
				"width": 1920,
				"height": 1080
			}]
		  },
		  {
			"label": "Configurator step calculator send-dealer popup",
			"cookiePath": "",
			"url": "http://hyundai/configurator/car/23/summary",
			"referenceUrl": "",
			"readyEvent": "",
			"readySelector": "",
			"delay": 5500,
			"onReadyScript": "puppet/onReady.js",
			"hideSelectors": [],
			"removeSelectors": [],
			"hoverSelector": "",
			"clickSelector": [".test-calc-button", ".program-item__send-dealer"],
			"postInteractionWait": 5000,
			"selectors": [],
			"selectorExpansion": true,
			"expect": 0,
			"misMatchThreshold" : 0.1,
			"requireSameDimensions": true,
			"viewports": [{
				"label": "desctop",
				"width": 1920,
				"height": 1080
			}]
		  },
		  {
			"label": "Configurator step calculator favorits",
			"cookiePath": "",
			"url": "http://hyundai/configurator/car/23/summary",
			"referenceUrl": "",
			"readyEvent": "",
			"readySelector": "",
			"delay": 5500,
			"onReadyScript": "puppet/onReady.js",
			"hideSelectors": [],
			"removeSelectors": [],
			"hoverSelector": "",
			"clickSelector": [".test-compare-button"],
			"postInteractionWait": 5000,
			"selectors": [],
			"selectorExpansion": true,
			"expect": 0,
			"misMatchThreshold" : 0.1,
			"requireSameDimensions": true,
		  }
	],
}