module.exports = {
	"scenarios": [
		  {
			"label": "Configurator step 3",
			"cookiePath": "",
			"url": "http://hyundai/configurator/car/23/complectation",
			"referenceUrl": "",
			"readyEvent": "",
			"readySelector": ".complectation-list",
			"delay": 2500,
			"hideSelectors": [],
			"removeSelectors": [],
			"hoverSelector": "",
			"clickSelector": [],
			"postInteractionWait": 0,
			"selectors": [],
			"selectorExpansion": true,
			"expect": 0,
			"misMatchThreshold" : 0.1,
			"requireSameDimensions": true
		  },
		  {
			"label": "Configurator step 4",
			"cookiePath": "",
			"url": "http://hyundai/configurator/car/23/complectation",
			"referenceUrl": "",
			"readyEvent": "",
			"readySelector": ".complectation-item:nth-of-type(3)",
			"delay": 1000,
			"onReadyScript": "puppet/onReady.js",
			"hideSelectors": [],
			"removeSelectors": [],
			"hoverSelector": "",
			"clickSelector": [".complectation-item:nth-of-type(3)", ".content-footer__button"],
			"postInteractionWait": 2000,
			"selectors": [],
			"selectorExpansion": true,
			"expect": 0,
			"misMatchThreshold" : 0.1,
			"requireSameDimensions": true
		  },
		  {
			"label": "Configurator step conf compare",
			"cookiePath": "",
			"url": "http://hyundai/configurator/car/23/complectation",
			"referenceUrl": "",
			"readyEvent": "",
			"readySelector": ".complectation-item",
			"delay": 2000,
			"onReadyScript": "puppet/onReady.js",
			"hideSelectors": [],
			"removeSelectors": [],
			"hoverSelector": "",
			"clickSelector": [".complectation-item .df-iconed-link"],
			"postInteractionWait": 5000,
			"selectors": [],
			"selectorExpansion": true,
			"expect": 0,
			"misMatchThreshold" : 0.1,
			"requireSameDimensions": true
		  }
	],
}